spring.application.name=JewelryStoreManagementSystem
spring.thymeleaf.cache=false

db.sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=JewelryStoreDB;encrypt=false;trustServerCertificate=true
db.sqlserver.username=sa
db.sqlserver.password=123

spring.datasource.url=${db.sqlserver.url}
spring.datasource.username=${db.sqlserver.username}
spring.datasource.password=${db.sqlserver.password}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.data-source-properties.encrypt=false
spring.datasource.hikari.data-source-properties.trustServerCertificate=true
